### ISSUE TITLE
Mega.nz xLODGen link down

### ISSUE THREAD

**Issue by brbrainerd** [jdsmith2816/emw#203]
Wabbajack fails to download the "Enderal - My Way" pack because xLODGEN.76.7z (linked to https://mega.nz/file/oVplUSpZ#RuT0KTyW3TCqDs4NcIRy3-RtGjPOtHcGYOJkLmpv1TY) was deleted from Mega.nz.  Log:

42.46 - Loading server whitelist
42.61 - Loaded permissions for 438 servers and 170 Google Drive files
42.61 - File hash check (-42) 85c2bb17e0cd014821477a06adeb533668eb41fd7706495cc2dbb1824dfd009a
42.61 - Vacuuming databases
42.62 - Vacuuming completed
42.63 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/oVplUSpZ#RuT0KTyW3TCqDs4NcIRy3-RtGjPOtHcGYOJkLmpv1TY failed validation
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 216
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 139
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373

**Comment by jdsmith2816** [comment]
Thanks; will be fixed in the next release but not sure yet when that will be.
